# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSBridgeStudy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'WebViewJavascriptBridge'
  # Pods for JSBridgeStudy

  target 'JSBridgeStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSBridgeStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
